version: '3'

tasks:
  install:
    cmds:
      - go install cmd/go-autoeq.go
      - cmd: echo "Go-AutoEQ ha sido instalado en $(go env GOPATH)/bin"
        silent: true

  check:
    cmds:
      - go build -o /dev/null pkg/*/*.go
      - go build -o /dev/null cmd/*.go
      - cmd: echo '¡Comprobación finalizada con éxito!'
        silent: true

  installdeps:
    cmds:
      - go mod download

  test:
    cmds:
      - go test -v ./...
    env:
      LOGPATH: /tmp/go-autoeq-test.log

  fmt:
    cmds:
      - go fmt cmd/*.go
      - go fmt pkg/*/*.go
